// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAeJYEtN5A7XNQp-5_RkolsBrqBKNSNMOQ',
    appId: '1:427159389841:web:92f9038e7f266b26fda130',
    messagingSenderId: '427159389841',
    projectId: 'ecommerceapp-6df02',
    authDomain: 'ecommerceapp-6df02.firebaseapp.com',
    storageBucket: 'ecommerceapp-6df02.firebasestorage.app',
    measurementId: 'G-SX6MB4Z54P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJK8y33OGSFBI_McyptTBxIf1R3VgSAiQ',
    appId: '1:427159389841:android:8c1909fd830cb546fda130',
    messagingSenderId: '427159389841',
    projectId: 'ecommerceapp-6df02',
    storageBucket: 'ecommerceapp-6df02.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHZyO8JA4UMw-Ynfk-LGIJFIQfga36cO4',
    appId: '1:427159389841:ios:2ed90c5038b02b05fda130',
    messagingSenderId: '427159389841',
    projectId: 'ecommerceapp-6df02',
    storageBucket: 'ecommerceapp-6df02.firebasestorage.app',
    androidClientId: '427159389841-46hn4q4mb5mp4gsqa26lekhm4rvpns9q.apps.googleusercontent.com',
    iosClientId: '427159389841-sup83qepkorgjq1hptl08ncl3n9ej06i.apps.googleusercontent.com',
    iosBundleId: 'com.example.abEcommerceAdminPanel',
  );
}
